apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: db-role-binding
 namespace: data-base
subjects:
  - kind: ServiceAccount
    name: db-service-account
    namespace: data-base
roleRef:
 kind: Role
 name: role-data-base      
 apiGroup: rbac.authorization.k8s.io
