apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
       - name: connect-db
         image: busybox
         command:
          - sh
          - -c 
          - |
             until nc -z mongo-service.default.svc.cluster.local 27017; do
             echo "Aguardando conexão com o MongoDB...";
             sleep 3;
             done   
      containers:
      - name: api-container
        image: patrickpk4/catalogo:v1.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "70m"
        ports:
        - containerPort: 80
          name: http 
        - containerPort: 443
          name: https 
        imagePullPolicy: Always
        readinessProbe:
         httpGet:
           path: /read
           port: 80
           scheme: HTTP 
         periodSeconds: 5
         timeoutSeconds: 2
         failureThreshold: 5  
        livenessProbe:
         httpGet:
           path: /health
           port: 80
           scheme: HTTP
         periodSeconds: 5
         timeoutSeconds: 2
         failureThreshold: 5 
        envFrom:
        - secretRef:
           name: catalogo-secret
        env: 
         - name: mongo_user
           valueFrom:
            secretKeyRef:
               key: MONGO_INITDB_ROOT_USERNAME
               name: mongodb-secret 
         - name: mongo_password
           valueFrom:
            secretKeyRef:
               key: MONGO_INITDB_ROOT_PASSWORD
               name: mongodb-secret  
         