apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
 name: role-catalogo
 namespace: api-app
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "list"]
 - apiGroups: [""]
   resources: ["services"]
   verbs: ["get"]
 - apiGroups: [""]
   resources: ["secrets"]
   verbs: ["get"]
   resourceNames: ["catalogo-secret"]
 #- apiGroups: ["apps"]
 #  resources: ["deployments"]
 #  verbs: ["get", "list"]
  